version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/cart
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
volumes:
  redis: {}
