version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/cart
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6379'
    volumes:
      - redis:/var/lib/redis/data
volumes:
  redis:
